version: '3.8'

services:
  dyn-dns:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      URL: ${URL}
      INTERVAL: ${INTERVAL}
    container_name: dyn-dns-service
    restart: unless-stopped