version: '3.8'

services:
  dyn-dns:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      URL: ${URL}
      INTERVAL: ${INTERVAL}
    ports:
      - '3333:3333'
    container_name: dyn-dns-service
    restart: unless-stopped
