version: '3.8'

services:
  app:
    build: .
    container_name: go-app
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production