version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GOPROXY=https://proxy.golang.org,direct
    ports:
      - "8080:8080"
    volumes:
      - ./:/app